'use strict';

const EULA_VERSION = '1.2';

const EULA_TEXT = `
END USER LICENSE AGREEMENT

Last Updated: May 10, 2026

IMPORTANT - READ CAREFULLY BEFORE USING THIS SOFTWARE.

This End User License Agreement ("Agreement") is a binding legal agreement between you ("User," "you," or "your") and Lavelle Hatcher Jr ("Developer," "we," "us," or "our") governing your use of the GlowReadTTS browser extension ("Software"), including any updates, patches, or modifications thereto.

BY CLICKING "ACCEPT & CONTINUE," YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY ALL TERMS AND CONDITIONS OF THIS AGREEMENT AND THE ACCOMPANYING PRIVACY POLICY. IF YOU DO NOT AGREE TO THESE TERMS, CLICK "DECLINE" AND DO NOT USE THE SOFTWARE. THE SOFTWARE WILL NOT ACTIVATE UNLESS YOU ACCEPT THESE TERMS.


SECTION 1: LICENSE GRANT AND SCOPE

1.1 The Developer grants you a limited, non-exclusive, non-transferable, revocable, royalty-free license to install and use the Software on devices running a compatible version of the Google Chrome browser, solely for lawful personal or commercial text-to-speech purposes, subject to the terms and restrictions of this Agreement.

1.2 The Software's source code is separately available under the Apache License 2.0. This EULA governs your use of the compiled and distributed extension obtained through the Chrome Web Store or the Developer's official GitHub repository. In the event of a conflict between this EULA and the Apache License 2.0 as applied to the source code, this EULA governs the end-user relationship for the distributed Software.


SECTION 2: PERMITTED USES

2.1 You may use the Software to:
(a) Convert text to speech for personal reading, learning, accessibility, or productivity purposes.
(b) Use the bundled AI voice model for local, on-device text-to-speech synthesis.
(c) Read aloud text from webpages and text pasted or typed into the Software's interface.


SECTION 3: PROHIBITED USES AND AI VOICE RESTRICTIONS

3.1 GENERAL PROHIBITIONS. You shall not use the Software to:
(a) Engage in, facilitate, or promote any activity that violates applicable local, state, national, or international law.
(b) Generate speech for the purpose of fraud, scams, phishing, social engineering, or any form of deception.
(c) Impersonate any real person, living or deceased, or create audio that could reasonably be mistaken for a real person's speech without that person's explicit written consent.
(d) Create, distribute, or facilitate the creation of deepfake audio, synthetic media intended to deceive, or non-consensual voice replications.
(e) Generate speech that constitutes defamation, harassment, threats, hate speech, or incitement to violence.
(f) Generate speech that infringes on any third party's intellectual property rights, including but not limited to copyrights, trademarks, or rights of publicity.
(g) Reproduce copyrighted audio content, including but not limited to audiobooks, podcasts, music lyrics, or broadcast content.
(h) Use the Software to circumvent any access controls, paywalls, or digital rights management systems.
(i) Use the Software in any manner that violates the terms of service of any website from which text is extracted.
(j) Interfere with, disrupt, or place undue burden on any network, server, or system through use of the Software.

3.2 AI VOICE SPECIFIC PROHIBITIONS. The AI voice functionality included in the Software uses pre-trained neural network models that generate synthetic speech. You additionally shall not:
(a) Use AI-generated speech to create content that violates any applicable synthetic media, deepfake, or AI transparency law, including but not limited to Japan's AI Promotion Act, the EU AI Act (Article 50), the US TAKE IT DOWN Act, state-level deepfake legislation (including but not limited to Tennessee's ELVIS Act, California's AI Transparency Act, and similar statutes in other jurisdictions), or any equivalent law in your jurisdiction.
(b) Distribute AI-generated speech without appropriate disclosure that the audio was synthetically generated, where such disclosure is required by applicable law.
(c) Use AI-generated speech to manipulate elections, deceive voters, or create false political communications.
(d) Attempt to use the Software to clone, replicate, or approximate any specific person's voice. The Software does not support voice cloning and any attempt to use it for this purpose is a violation of this Agreement.
(e) Use AI-generated speech output in any commercial product, service, or broadcast without independently verifying compliance with all applicable synthetic media and AI disclosure laws in your jurisdiction.

3.3 COMPLIANCE RESPONSIBILITY. You are solely responsible for ensuring that your use of the Software and any speech output generated by the Software complies with all applicable laws and regulations in your jurisdiction. The Developer makes no representation that the Software or its output complies with the laws of any particular jurisdiction.


SECTION 4: INTELLECTUAL PROPERTY

4.1 The Software, excluding third-party components identified in the NOTICE file, is the intellectual property of the Developer and is protected by applicable copyright, trademark, and other intellectual property laws.

4.2 "GlowReadTTS" is an unregistered trademark of the Developer. You may not use the name "GlowReadTTS" or any confusingly similar name for any other product or service without the Developer's prior written consent.

4.3 Third-party components included in the Software (including but not limited to ONNX Runtime Web and the AI voice model) are the property of their respective owners and are subject to their respective licenses as identified in the NOTICE file.

4.4 Any speech audio generated by the Software is a derivative output of the AI model and/or the operating system's speech engine. The Developer makes no claim of ownership over audio generated by you through the Software and makes no warranty regarding the intellectual property status of such generated audio.


SECTION 5: THIRD-PARTY CONTENT AND WEBSITES

5.1 The Software may be used to read text from third-party websites. The Developer is not affiliated with, endorsed by, or responsible for any third-party content.

5.2 You acknowledge that certain websites may prohibit automated text extraction, scraping, or text-to-speech conversion through their terms of service, robots.txt files, or other mechanisms. You are solely responsible for complying with the terms of service of any website you access using the Software.

5.3 The Developer shall not be liable for any claims arising from your extraction, processing, or conversion of third-party content to speech, including but not limited to claims of copyright infringement, terms of service violation, or unauthorized access.


SECTION 6: DISCLAIMER OF WARRANTIES

6.1 THE SOFTWARE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, TITLE, ACCURACY, OR QUIET ENJOYMENT.

6.2 THE DEVELOPER DOES NOT WARRANT THAT:
(a) THE SOFTWARE WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS;
(b) THE SOFTWARE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE;
(c) THE RESULTS OBTAINED FROM USE OF THE SOFTWARE WILL BE ACCURATE, RELIABLE, OR COMPLETE;
(d) ANY ERRORS IN THE SOFTWARE WILL BE CORRECTED;
(e) THE SOFTWARE WILL BE COMPATIBLE WITH ANY PARTICULAR HARDWARE OR SOFTWARE CONFIGURATION;
(f) THE AI VOICE OUTPUT WILL BE FREE FROM MISPRONUNCIATIONS, ARTIFACTS, OR DISTORTIONS;
(g) THE SOFTWARE WILL FUNCTION ON ALL WEBSITES.

6.3 ACCESSIBILITY DISCLAIMER. THE SOFTWARE IS DESIGNED TO ASSIST WITH TEXT-TO-SPEECH CONVERSION BUT IS NOT A MEDICAL DEVICE, ASSISTIVE TECHNOLOGY DEVICE AS DEFINED BY ANY REGULATORY BODY, OR A SUBSTITUTE FOR PROFESSIONAL ACCESSIBILITY SERVICES. THE SOFTWARE HAS NOT BEEN CERTIFIED, TESTED, OR APPROVED UNDER ANY ACCESSIBILITY STANDARD INCLUDING BUT NOT LIMITED TO WCAG, ADA, SECTION 508, OR EN 301 549. USERS WITH ACCESSIBILITY NEEDS SHOULD NOT RELY SOLELY ON THIS SOFTWARE AND SHOULD CONSULT APPROPRIATE ACCESSIBILITY PROFESSIONALS.

6.4 AI MODEL DISCLAIMER. THE AI VOICE MODEL USED BY THE SOFTWARE IS A THIRD-PARTY OPEN-SOURCE MODEL DISTRIBUTED UNDER THE APACHE LICENSE 2.0. THE DEVELOPER DID NOT CREATE, TRAIN, OR VALIDATE THE MODEL AND MAKES NO WARRANTY REGARDING ITS ACCURACY, SAFETY, QUALITY, OR FITNESS FOR ANY PURPOSE. THE DEVELOPER IS NOT RESPONSIBLE FOR ANY OUTPUTS PRODUCED BY THE MODEL.


SECTION 7: LIMITATION OF LIABILITY

7.1 TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE DEVELOPER, OR ANY OF THE DEVELOPER'S AGENTS, AFFILIATES, SUCCESSORS, OR ASSIGNS, BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY:
(a) INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES;
(b) LOSS OF PROFITS, REVENUE, DATA, USE, GOODWILL, BUSINESS OPPORTUNITIES, OR ANTICIPATED SAVINGS;
(c) COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
(d) PERSONAL INJURY OR PROPERTY DAMAGE RELATED TO YOUR USE OF THE SOFTWARE;
(e) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR DATA OR TRANSMISSIONS;
(f) CLAIMS ARISING FROM YOUR MISUSE OF AI-GENERATED SPEECH, INCLUDING BUT NOT LIMITED TO CLAIMS RELATED TO DEEPFAKES, IMPERSONATION, FRAUD, DEFAMATION, OR VIOLATIONS OF SYNTHETIC MEDIA LAWS;
(g) CLAIMS ARISING FROM YOUR VIOLATION OF ANY THIRD-PARTY WEBSITE'S TERMS OF SERVICE;
(h) ANY DAMAGES ARISING FROM YOUR RELIANCE ON THE SOFTWARE FOR ACCESSIBILITY PURPOSES;
WHETHER ARISING OUT OF BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR ANY OTHER LEGAL THEORY, WHETHER OR NOT THE DEVELOPER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

7.2 THE DEVELOPER'S TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THIS AGREEMENT OR YOUR USE OF THE SOFTWARE SHALL NOT EXCEED THE GREATER OF (A) THE TOTAL AMOUNT YOU PAID FOR THE SOFTWARE, OR (B) ZERO US DOLLARS ($0.00 USD).

7.3 SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IN SUCH JURISDICTIONS, THE DEVELOPER'S LIABILITY SHALL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW.


SECTION 8: INDEMNIFICATION

8.1 You agree to defend, indemnify, and hold harmless the Developer and the Developer's agents, affiliates, successors, and assigns from and against any and all claims, damages, obligations, losses, liabilities, costs, and expenses (including but not limited to attorney's fees and legal costs) arising from or related to:
(a) Your use or misuse of the Software;
(b) Your violation of any term of this Agreement;
(c) Your violation of any applicable law, rule, or regulation, including but not limited to deepfake, synthetic media, privacy, copyright, defamation, or right of publicity laws;
(d) Your violation of any third party's rights, including intellectual property rights, privacy rights, or rights of publicity;
(e) Any content you generate, process, extract, or distribute using the Software;
(f) Any claim that speech audio you generated using the Software caused harm to any third party;
(g) Your failure to comply with applicable synthetic media disclosure requirements.


SECTION 9: DISPUTE RESOLUTION

9.1 INFORMAL RESOLUTION. Before initiating any formal legal proceeding, you agree to first contact the Developer at the contact information provided in the Privacy Policy and attempt to resolve the dispute informally for a period of at least thirty (30) days.

9.2 GOVERNING LAW. This Agreement shall be governed by and construed in accordance with the laws of Japan, without regard to conflict of law principles.

9.3 JURISDICTION. Any legal action or proceeding arising under this Agreement shall be brought exclusively in the courts of Japan having jurisdiction over the Developer's place of residence, and you hereby consent to the personal jurisdiction and venue of such courts.

9.4 WAIVER OF CLASS ACTION. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, YOU AGREE THAT ANY DISPUTE RESOLUTION PROCEEDINGS WILL BE CONDUCTED ONLY ON AN INDIVIDUAL BASIS AND NOT IN A CLASS, CONSOLIDATED, OR REPRESENTATIVE ACTION. IF THIS CLASS-ACTION WAIVER IS FOUND TO BE UNENFORCEABLE BY A COURT OF COMPETENT JURISDICTION, THIS PROVISION ALONE SHALL BE SEVERED FROM THIS AGREEMENT, AND THE REMAINDER OF THIS SECTION 9 (INCLUDING THE GOVERNING LAW, JURISDICTION, INFORMAL RESOLUTION, AND LIMITATION-OF-CLAIMS PROVISIONS) SHALL CONTINUE IN FULL FORCE AND EFFECT.

9.5 LIMITATION ON TIME TO FILE CLAIMS. ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THIS AGREEMENT OR THE SOFTWARE MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION OR CLAIM IS PERMANENTLY BARRED.


SECTION 10: TERMINATION

10.1 This Agreement is effective until terminated. You may terminate this Agreement at any time by uninstalling the Software and destroying all copies in your possession.

10.2 The Developer may terminate this Agreement immediately, without notice, if you breach any provision of this Agreement. Upon termination, your license to use the Software is immediately revoked.

10.3 The Developer may, at the Developer's sole discretion, cease distribution, support, or development of the Software at any time without liability to you.

10.4 Sections 3 (Prohibited Uses), 4 (Intellectual Property), 6 (Disclaimer of Warranties), 7 (Limitation of Liability), 8 (Indemnification), 9 (Dispute Resolution), and this Section 10.4 shall survive termination of this Agreement.


SECTION 11: MODIFICATIONS TO THIS AGREEMENT

11.1 The Developer reserves the right to modify this Agreement at any time. Material changes will be communicated by presenting the updated Agreement within the Software upon your next use, requiring your acceptance of the new terms to continue using the Software.

11.2 Your continued use of the Software after acceptance of modified terms constitutes your agreement to the modified terms.

11.3 If you do not agree to modified terms, you must discontinue use of the Software and uninstall it.


SECTION 12: GENERAL PROVISIONS

12.1 ENTIRE AGREEMENT. This Agreement, together with the Privacy Policy, constitutes the entire agreement between you and the Developer regarding the Software and supersedes all prior or contemporaneous agreements, representations, warranties, and understandings.

12.2 SEVERABILITY. If any provision of this Agreement is held to be unenforceable or invalid by a court of competent jurisdiction, that provision shall be modified to the minimum extent necessary to make it enforceable, or if modification is not possible, severed from this Agreement. All remaining provisions shall continue in full force and effect.

12.3 WAIVER. The failure of the Developer to exercise or enforce any right or provision of this Agreement shall not constitute a waiver of such right or provision.

12.4 ASSIGNMENT. You may not assign or transfer this Agreement or any rights or obligations hereunder without the Developer's prior written consent. The Developer may freely assign this Agreement.

12.5 NO THIRD-PARTY BENEFICIARIES. This Agreement does not create any third-party beneficiary rights.

12.6 EXPORT COMPLIANCE. You agree to comply with all applicable export and re-export control laws and regulations. You represent and warrant that you are not located in a country subject to a US government embargo or that has been designated as a "terrorist supporting" country, and that you are not listed on any US government list of prohibited or restricted parties.

12.7 FORCE MAJEURE. The Developer shall not be liable for any failure or delay in performance due to causes beyond the Developer's reasonable control, including but not limited to acts of God, natural disasters, pandemic, war, terrorism, riots, government actions, or failures of third-party services.

12.8 CONTACT. For questions about this Agreement, contact the Developer via the GitHub Issues page for the GlowReadTTS repository.
`;

const PRIVACY_TEXT = `
PRIVACY POLICY

Last Updated: July 28, 2026

Lavelle Hatcher Jr ("Developer," "we," "us," or "our") operates the GlowReadTTS browser extension ("Software"). This Privacy Policy describes how we handle information when you use the Software. By using the Software, you agree to the practices described in this Privacy Policy.


SECTION 1: INFORMATION WE DO NOT COLLECT

1.1 We do not collect, store, transmit, sell, rent, lease, or process any personal information or personally identifiable information (PII). Specifically:
(a) We do not collect your name, email address, phone number, mailing address, or any identifying information.
(b) We do not collect, transmit, or store any text you process through the Software, including text you type, paste, or select on a webpage.
(c) We do not collect browsing history, URLs visited, webpage content, or any browsing activity data.
(d) We do not use cookies, web beacons, analytics services, tracking pixels, fingerprinting, or any tracking technology.
(e) We do not collect device identifiers, hardware information, IP addresses, geolocation data, or operating system information.
(f) We do not sell, share, rent, lease, or transfer any user data to any third party for any purpose, including advertising, marketing, data brokerage, or analytics.
(g) We do not collect biometric data, voice data, or any other sensitive personal information.
(h) We do not collect or process data about children or minors.


SECTION 2: LOCAL DATA PROCESSING

2.1 All text-to-speech processing occurs entirely and exclusively on your local device:
(a) AI Voice Synthesis: Text is processed by a neural network model (Kokoro 82M) running locally on your device via WebAssembly (ONNX Runtime Web) inside an offscreen document. The model weights and all voice embeddings are bundled inside the extension package; no runtime download is required and no text is transmitted to any external server.

2.2 The Software has no backend servers, no cloud infrastructure, no databases, and no server-side code. There is no server to which data could be transmitted.


SECTION 3: DATA STORED LOCALLY ON YOUR DEVICE

3.1 The Software stores the following data locally using Chrome's built-in storage APIs. All data listed below is stored exclusively on your device and is automatically and permanently deleted when the Software is uninstalled:
(a) Voice and speed preferences (chrome.storage.sync) - synced across your Chrome devices if Chrome sync is enabled (this is a Chrome feature, not controlled by the Software).
(b) EULA/Privacy Policy acceptance state (chrome.storage.local) - records that you accepted these terms, the version accepted, and the date of acceptance.
(c) Selection-prewarm preference (chrome.storage.local) - a single boolean (prewarmOnSelection) that controls whether the AI voice model preloads when you select text on a page. Stored only on this device - never syncs to any server.
(d) Session text for playback continuity (sessionStorage) - temporarily stores the most recently read text. This is automatically cleared when the popup is closed.
(e) Transient internal state flags (chrome.storage.session) - a small set of booleans (playbackActive, aiPrewarmReady, offscreenReady) used internally to surface the "Reading in progress" banner when the popup reopens during an active read, to track whether the AI voice model has finished loading for the current browser session, and to coordinate the Software's own components. Individual flags are cleared as soon as they are no longer needed (for example, playbackActive is cleared when audio ends or is stopped), and all of them are cleared automatically when the browser closes. These flags contain no user content or identifying information.

3.2 No data stored by the Software is accessible to other extensions, websites, or applications. Chrome's storage APIs are sandboxed to the extension's unique origin.


SECTION 4: NETWORK REQUESTS

4.1 The Software makes NO network requests during normal operation. All processing - including AI voice synthesis using the bundled Kokoro neural network - happens locally on your device.

4.2 The AI voice model and voice embeddings are bundled inside the extension package at install time. No runtime download from huggingface.co or any other server is required.

4.3 The Software does not contact any analytics services, advertising networks, crash reporting services, update servers, or any other external endpoints.


SECTION 5: PERMISSIONS JUSTIFICATION

5.1 The Software requests the following Chrome browser permissions. Each permission is used solely for the purpose described below:
(a) "storage" - to save your voice and speed preferences locally on your device.
(b) "activeTab" - to read selected text from the currently active browser tab when you explicitly request a right-click read via the "Read with GlowReadTTS" menu item.
(c) "contextMenus" - to add the "Read with GlowReadTTS" option to the right-click context menu.
(d) "notifications" - to surface a brief "Preparing audio..." toast on the first AI right-click read of a session.
(e) "offscreen" - to host the audio playback and the on-device neural inference Web Worker in a document that survives the popup closing.
(f) "scripting" - to inject the highlight-as-you-read content script on tabs that don't already have it loaded (e.g., tabs that were open before the Software was installed or reloaded).
(g) "<all_urls>" host permission - required for the content script to operate on any webpage the user visits, so that the right-click "Read with GlowReadTTS" action and its highlight-as-you-read functionality work on all websites. This permission does NOT grant the Software automatic access to page content; selected text is only accessed when the user explicitly triggers a reading action via the right-click menu.

5.2 No permission is used to monitor, collect, log, or transmit browsing activity, page content, user data, or any other information.


SECTION 6: THIRD-PARTY SERVICES

6.1 Google Chrome APIs: The Software uses Chrome's built-in APIs (chrome.storage, chrome.contextMenus, chrome.scripting, chrome.offscreen, chrome.notifications). These APIs are provided by Google and subject to Google's terms of service and privacy policy. The Developer is not responsible for how Chrome or Google handles data processed through these APIs. The Software does NOT use Chrome's chrome.tts API and does NOT send any text to remote / network speech engines.


SECTION 7: CHILDREN'S PRIVACY

7.1 The Software does not knowingly collect, process, or store any information from anyone, including children under the age of 13 (or the applicable age of digital consent in your jurisdiction).

7.2 If you are under the age of 13 (or the applicable age of digital consent in your jurisdiction), you may use the Software only with the involvement and consent of a parent or legal guardian.


SECTION 8: INTERNATIONAL PRIVACY LAW COMPLIANCE

8.1 APPI (Japan, Primary Applicable Law): The Developer is based in Japan, and the Act on the Protection of Personal Information ("APPI") is the primary privacy framework applicable to the Developer's operation of the Software. The Software does not collect, process, transfer, or disclose personal information as defined under APPI Article 2. Because no personal information is handled, the obligations applicable to Personal Information Controllers under APPI Articles 17 through 28 (including obligations regarding purpose specification, consent for sensitive personal information, third-party transfers, and cross-border data transfers) do not arise from operation of the Software. The Software's zero-data-collection design ensures full compliance with APPI's principles of necessity, purpose limitation, and data minimization.

8.2 GDPR (European Union / European Economic Area / United Kingdom): The Software does not collect or process personal data as defined by the General Data Protection Regulation (EU) 2016/679 or the UK GDPR. As no personal data is processed, the legal bases for processing (Article 6), data subject rights (Articles 15-22), and data processing agreements (Article 28) do not apply. No data is transferred outside of your device.

8.3 CCPA / CPRA (California, United States): The Software does not sell, share, or collect personal information as defined under the California Consumer Privacy Act (Cal. Civ. Code § 1798.100 et seq.) or the California Privacy Rights Act. The Software does not engage in cross-context behavioral advertising or profiling.

8.4 OTHER JURISDICTIONS: The Software's zero-data-collection design is intended to comply with privacy laws in all jurisdictions. Because no personal data is collected, transmitted, or processed, the Software imposes no data-related obligations on the user or the Developer beyond those described in this Privacy Policy.


SECTION 9: AI-GENERATED CONTENT TRANSPARENCY

9.1 In accordance with emerging AI transparency requirements (including EU AI Act Article 50 and various state-level synthetic media laws), users should be aware that:
(a) The AI voices provided by the Software generate synthetic speech. Audio produced by the AI voice feature is machine-generated and not a recording of any real person.
(b) The AI voice model was trained on permissive/non-copyrighted audio data as described in the model's official documentation.
(c) The Software does not support voice cloning, voice replication, or generating speech that mimics any specific real person's voice.
(d) Users who distribute AI-generated speech output may be subject to synthetic media disclosure requirements in their jurisdiction.


SECTION 10: DATA SECURITY

10.1 All data stored by the Software resides locally on your device within Chrome's sandboxed extension storage, which is isolated from other extensions and websites.

10.2 The Software does not implement its own encryption for locally stored data (such as voice preferences) because Chrome's extension storage APIs provide origin-level isolation. No sensitive personal data is stored.

10.3 The Software does not have access to your passwords, financial information, authentication tokens, or any other credentials.


SECTION 11: DATA RETENTION AND DELETION

11.1 The Software does not retain any user data beyond the current browser session, with the exception of the locally stored preferences described in Section 3.

11.2 All data stored by the Software is automatically and permanently deleted when the Software is uninstalled from Chrome.


SECTION 12: CHANGES TO THIS PRIVACY POLICY

12.1 We may update this Privacy Policy from time to time. If we make material changes, the updated Privacy Policy will be presented to you within the Software upon your next use, and you will be required to review and accept the new terms to continue using the Software.

12.2 The "Last Updated" date at the top of this Privacy Policy indicates when it was last revised.

12.3 We encourage you to review this Privacy Policy periodically.


SECTION 13: CONTACT INFORMATION

13.1 If you have questions, concerns, or requests regarding this Privacy Policy, you may contact the Developer via the GitHub Issues page for the GlowReadTTS repository.


SECTION 14: CHROME WEB STORE COMPLIANCE

14.1 The use of information received from Chrome APIs adheres to the Chrome Web Store User Data Policy, including the Limited Use requirements.

14.2 The Software's use of the "activeTab" and "<all_urls>" permissions is limited to the core functionality of reading webpage text aloud and providing highlight-as-you-read visual feedback, as described in the Software's Chrome Web Store listing.
`;

// Render the policy text safely via textContent (never innerHTML).
document.getElementById('eula-text').textContent = EULA_TEXT;
document.getElementById('privacy-text').textContent = PRIVACY_TEXT;

const content = document.getElementById('eula-content');
const checkbox = document.getElementById('eula-checkbox');
const acceptBtn = document.getElementById('btn-accept');
const declineBtn = document.getElementById('btn-decline');
const scrollNotice = document.getElementById('scroll-notice');

// Unlock the checkbox only after the user has scrolled to the bottom of the
// policy. A 20px tolerance handles sub-pixel rounding on hi-DPI displays.
function checkScrolledToBottom() {
  const atBottom = content.scrollTop + content.clientHeight >= content.scrollHeight - 20;
  if (atBottom) {
    checkbox.disabled = false;
    scrollNotice.classList.add('hidden');
  }
}

content.addEventListener('scroll', checkScrolledToBottom);

// Some viewports are tall enough that the content fits without scrolling. In
// that case the user has already "read" everything visible, so unlock immediately.
window.addEventListener('load', () => {
  if (content.scrollHeight <= content.clientHeight + 20) {
    checkbox.disabled = false;
    scrollNotice.classList.add('hidden');
  }
});

checkbox.addEventListener('change', () => {
  acceptBtn.disabled = !checkbox.checked;
});

acceptBtn.addEventListener('click', async () => {
  // First-run onboarding: if the user has never been shown the
  // getting-started guide before, open it in a new tab right after
  // they accept. This is the only place the right-click feature
  // (the primary entry point) is documented in plain language -
  // most users never discover it from the popup alone.
  // The flag is set BEFORE we open the tab so re-acceptance on
  // version bumps doesn't reopen it.
  const prior = await chrome.storage.local.get('onboarding_shown');
  await chrome.storage.local.set({
    eula_accepted: true,
    eula_version: EULA_VERSION,
    eula_accepted_date: new Date().toISOString(),
    onboarding_shown: true
  });
  if (!prior.onboarding_shown) {
    try {
      chrome.tabs.create({ url: chrome.runtime.getURL('help/getting-started.html') });
    } catch (e) { /* tab API unavailable; proceed to close anyway */ }
  }
  window.close();
});

declineBtn.addEventListener('click', async () => {
  await chrome.storage.local.set({ eula_accepted: false });
  renderDeclineMessage();
});

function renderDeclineMessage() {
  const container = document.querySelector('.eula-container');
  container.textContent = '';

  const wrapper = document.createElement('div');
  wrapper.style.cssText = 'text-align: center; padding: 60px 20px;';

  const heading = document.createElement('h2');
  heading.textContent = 'GlowReadTTS is not activated';
  heading.style.cssText = 'font-family: Georgia, "Times New Roman", serif; color: #1A1815;';

  const msg1 = document.createElement('p');
  msg1.textContent = 'You must accept the Terms of Use and Privacy Policy to use GlowReadTTS.';
  msg1.style.cssText = 'color: #6B6864; margin-top: 12px;';

  const msg2 = document.createElement('p');
  msg2.textContent = 'The extension will remain inactive until you accept the terms.';
  msg2.style.cssText = 'color: #6B6864; margin-top: 8px;';

  const msg3 = document.createElement('p');
  msg3.textContent = 'To review the terms again, click the GlowReadTTS icon in your toolbar.';
  msg3.style.cssText = 'color: #6B6864; margin-top: 8px;';

  const msg4 = document.createElement('p');
  msg4.textContent = 'You can uninstall GlowReadTTS from chrome://extensions if you do not wish to use it.';
  msg4.style.cssText = 'color: #8A8680; margin-top: 24px; font-size: 12px;';

  wrapper.append(heading, msg1, msg2, msg3, msg4);
  container.append(wrapper);
}
